import {
  BookOpen,
  Briefcase,
  Building2,
  Camera,
  Car,
  Coffee,
  Cpu,
  Factory,
  Globe,
  GraduationCap,
  Hammer,
  Heart,
  Home,
  Landmark,
  Leaf,
  type LucideIcon,
  Music,
  Palette,
  Plane,
  Scale,
  Scissors,
  Shield,
  ShoppingCart,
  Stethoscope,
  Store,
  Truck,
  Utensils,
  Wifi,
  Wrench,
  Zap,
} from 'lucide-react'
import type { BusinessType } from './EntitySearchTypes'

export const categoryEmojis: Record<string, string> = {
  technology: '\u{1F4BB}',
  software: '\u{1F310}',
  creative: '\u{1F3A8}',
  retail: '\u{1F6CD}\uFE0F',
  ecommerce: '\u{1F6D2}',
  food: '\u{1F37D}\uFE0F',
  hospitality: '\u2615',
  manufacturing: '\u{1F3ED}',
  logistics: '\u{1F69A}',
  healthcare: '\u{1F3E5}',
  education: '\u{1F393}',
  realestate: '\u{1F3E0}',
  construction: '\u{1F528}',
  services: '\u{1F527}',
  consulting: '\u{1F4BC}',
  finance: '\u{1F3E6}',
  legal: '\u2696\uFE0F',
  agriculture: '\u{1F331}',
  beauty: '\u2702\uFE0F',
  automotive: '\u{1F697}',
  energy: '\u26A1',
  travel: '\u2708\uFE0F',
  entertainment: '\u{1F3B5}',
  media: '\u{1F4F7}',
  security: '\u{1F6E1}\uFE0F',
  telecom: '\u{1F4E1}',
  publishing: '\u{1F4DA}',
  nonprofit: '\u2764\uFE0F',
  other: '\u{1F3E2}',
}

export const categoryIcons: Record<string, LucideIcon> = {
  technology: Cpu,
  software: Globe,
  creative: Palette,
  retail: Store,
  ecommerce: ShoppingCart,
  food: Utensils,
  hospitality: Coffee,
  manufacturing: Factory,
  logistics: Truck,
  healthcare: Stethoscope,
  education: GraduationCap,
  realestate: Home,
  construction: Hammer,
  services: Wrench,
  consulting: Briefcase,
  finance: Landmark,
  legal: Scale,
  agriculture: Leaf,
  energy: Zap,
  travel: Plane,
  entertainment: Music,
  media: Camera,
  beauty: Scissors,
  automotive: Car,
  security: Shield,
  telecom: Wifi,
  publishing: BookOpen,
  nonprofit: Heart,
  other: Building2,
}

// Business types (sample - full list from DB)
export const defaultBusinessTypes: BusinessType[] = [
  {
    id: 'tech-01',
    code: '62.010',
    name: 'Softwareontwikkeling',
    category: 'technology',
    icon: Cpu,
    description: 'Custom software development',
  },
  {
    id: 'tech-02',
    code: '62.020',
    name: 'IT-consultancy',
    category: 'technology',
    icon: Briefcase,
    description: 'Technology consulting services',
  },
  {
    id: 'tech-03',
    code: '63.110',
    name: 'Dataverwerking & hosting',
    category: 'software',
    icon: Globe,
    description: 'Data processing and web hosting',
  },
  {
    id: 'creat-01',
    code: '73.110',
    name: 'Reclamebureau',
    category: 'creative',
    icon: Palette,
    description: 'Advertising agency',
  },
  {
    id: 'creat-02',
    code: '74.201',
    name: 'Fotografie',
    category: 'creative',
    icon: Camera,
    description: 'Photography services',
  },
  {
    id: 'creat-03',
    code: '74.209',
    name: 'Grafisch ontwerp',
    category: 'creative',
    icon: Palette,
    description: 'Graphic design',
  },
  {
    id: 'ret-01',
    code: '47.110',
    name: 'Supermarkt',
    category: 'retail',
    icon: Store,
    description: 'Supermarket retail',
  },
  {
    id: 'ret-02',
    code: '47.710',
    name: 'Kledingwinkel',
    category: 'retail',
    icon: Store,
    description: 'Clothing retail',
  },
  {
    id: 'ret-03',
    code: '47.910',
    name: 'Webwinkel',
    category: 'ecommerce',
    icon: ShoppingCart,
    description: 'E-commerce retail',
  },
  {
    id: 'food-01',
    code: '56.101',
    name: 'Restaurant',
    category: 'food',
    icon: Utensils,
    description: 'Restaurant services',
  },
  {
    id: 'food-02',
    code: '56.102',
    name: 'Brasserie & Bistro',
    category: 'food',
    icon: Coffee,
    description: 'Casual dining',
  },
  {
    id: 'food-03',
    code: '56.301',
    name: 'Caf\u00e9',
    category: 'hospitality',
    icon: Coffee,
    description: 'Caf\u00e9 and bar',
  },
  {
    id: 'food-04',
    code: '10.710',
    name: 'Bakkerij',
    category: 'food',
    icon: Utensils,
    description: 'Bakery',
  },
  {
    id: 'food-05',
    code: '10.130',
    name: 'Slagerij',
    category: 'food',
    icon: Utensils,
    description: 'Butcher shop',
  },
  {
    id: 'mfg-01',
    code: '25.110',
    name: 'Metaalconstructie',
    category: 'manufacturing',
    icon: Factory,
    description: 'Metal construction',
  },
  {
    id: 'mfg-02',
    code: '31.010',
    name: 'Meubelproductie',
    category: 'manufacturing',
    icon: Factory,
    description: 'Furniture manufacturing',
  },
  {
    id: 'log-01',
    code: '49.410',
    name: 'Goederenvervoer',
    category: 'logistics',
    icon: Truck,
    description: 'Freight transport',
  },
  {
    id: 'log-02',
    code: '52.100',
    name: 'Opslag & warehousing',
    category: 'logistics',
    icon: Truck,
    description: 'Warehousing services',
  },
  {
    id: 'health-01',
    code: '86.210',
    name: 'Huisartsenpraktijk',
    category: 'healthcare',
    icon: Stethoscope,
    description: 'General practice',
  },
  {
    id: 'health-02',
    code: '86.230',
    name: 'Tandartspraktijk',
    category: 'healthcare',
    icon: Stethoscope,
    description: 'Dental practice',
  },
  {
    id: 'health-03',
    code: '86.901',
    name: 'Fysiotherapie',
    category: 'healthcare',
    icon: Heart,
    description: 'Physiotherapy',
  },
  {
    id: 'prof-01',
    code: '69.101',
    name: 'Advocatenkantoor',
    category: 'legal',
    icon: Scale,
    description: 'Law firm',
  },
  {
    id: 'prof-02',
    code: '69.201',
    name: 'Accountantskantoor',
    category: 'finance',
    icon: Landmark,
    description: 'Accounting firm',
  },
  {
    id: 'prof-03',
    code: '70.220',
    name: 'Managementadvies',
    category: 'consulting',
    icon: Briefcase,
    description: 'Management consulting',
  },
  {
    id: 'prof-04',
    code: '71.111',
    name: 'Architectenbureau',
    category: 'consulting',
    icon: Home,
    description: 'Architecture firm',
  },
  {
    id: 'con-01',
    code: '41.201',
    name: 'Woningbouw',
    category: 'construction',
    icon: Home,
    description: 'Residential construction',
  },
  {
    id: 'con-02',
    code: '43.210',
    name: 'Elektrotechniek',
    category: 'construction',
    icon: Zap,
    description: 'Electrical installation',
  },
  {
    id: 'con-03',
    code: '43.220',
    name: 'Loodgieterij',
    category: 'construction',
    icon: Wrench,
    description: 'Plumbing',
  },
  {
    id: 'beauty-01',
    code: '96.021',
    name: 'Kapsalon',
    category: 'beauty',
    icon: Scissors,
    description: 'Hair salon',
  },
  {
    id: 'beauty-02',
    code: '96.022',
    name: 'Schoonheidssalon',
    category: 'beauty',
    icon: Scissors,
    description: 'Beauty salon',
  },
  {
    id: 'auto-01',
    code: '45.111',
    name: 'Autohandel',
    category: 'automotive',
    icon: Car,
    description: 'Car dealership',
  },
  {
    id: 'auto-02',
    code: '45.200',
    name: 'Autogarage',
    category: 'automotive',
    icon: Car,
    description: 'Auto repair',
  },
  {
    id: 're-01',
    code: '68.310',
    name: 'Vastgoedmakelaar',
    category: 'realestate',
    icon: Home,
    description: 'Real estate brokerage',
  },
  {
    id: 're-02',
    code: '68.320',
    name: 'Vastgoedbeheer',
    category: 'realestate',
    icon: Home,
    description: 'Property management',
  },
]

export const categoryLabels: Record<string, string> = {
  technology: 'Technologie',
  software: 'Software',
  creative: 'Creatief',
  retail: 'Retail',
  ecommerce: 'E-commerce',
  food: 'Voeding',
  hospitality: 'Horeca',
  manufacturing: 'Productie',
  logistics: 'Logistiek',
  healthcare: 'Zorg',
  education: 'Onderwijs',
  realestate: 'Vastgoed',
  construction: 'Bouw',
  services: 'Diensten',
  consulting: 'Advies',
  finance: 'Financieel',
  legal: 'Juridisch',
  agriculture: 'Landbouw',
  beauty: 'Verzorging',
  automotive: 'Automotive',
  other: 'Overig',
}
