import { afterEach, describe, expect, it, vi } from 'vitest'
import type { NormalizationItem } from '../../components/calculator/UnifiedNormalizationTypes'
import { useTaxLatencyStore } from '../../store/useTaxLatencyStore'
import { buildValuationRequest } from '../buildValuationRequest'
import { makeFormData } from './buildValuationRequest.testUtils'

describe('Venus valuation input parity sentinel', () => {
  afterEach(() => {
    vi.useRealTimers()
    useTaxLatencyStore.getState().clear()
  })

  it('serializes the complete evidence-first Venus payload without losing priced inputs', () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-08-12T10:00:00Z'))

    const normalizations: NormalizationItem[] = [
      {
        id: 'norm-accepted',
        ledgerCode: '640100',
        ledgerName: 'One-off restructuring cost',
        category: 'one-time',
        type: 'add',
        value: 25_000,
        adjustment: 25_000,
        reason: 'Accepted by advisor against invoice INV-42',
        source: 'manual',
        sourceRef: 'evidence-invoice-42',
        status: 'accepted',
        reviewedAt: '2026-08-12T09:30:00Z',
        applyAllYears: false,
        year: 2025,
        confidence: 'high',
      },
      {
        id: 'norm-proposed',
        ledgerCode: '610200',
        ledgerName: 'Potential private rent add-back',
        category: 'rent',
        type: 'add',
        value: 10_000,
        adjustment: 10_000,
        reason: 'Awaiting lease evidence',
        source: 'manual',
        sourceRef: 'evidence-request-lease',
        status: 'pending',
        applyAllYears: false,
        year: 2025,
        confidence: 'low',
      },
    ]

    const request = buildValuationRequest(
      makeFormData({
        company_name: 'Evidence First Holdings',
        country_code: 'BE',
        currency: 'gbp',
        registration_number: '0123.456.789',
        kbo_number: '0123.456.789',
        vat_number: 'BE0123456789',
        legal_form: 'BV',
        postal_code: '1000',
        city: 'Brussels',
        nace_code: '64.20',
        nace_description: 'Holding companies',
        activity_code: '64.20',
        canonical_nace_code: '64.20',
        business_description: 'A governed operating and property holding group.',
        business_highlights: 'Recurring contracts and documented succession.',
        reason_for_selling: 'Partial succession transaction.',
        employee_count: 19,
        owners: 2,
        filing_year_confirmed: true,
        current_year_data: {
          year: 2025,
          revenue: 1_200_000,
          operating_revenue: 1_175_000,
          ebitda: 100_000,
          reported_ebitda: 100_000,
          cogs: 300_000,
          gross_profit: 900_000,
          financial_income: 12_000,
          extraordinary_income: 3_000,
          extraordinary_items: -2_000,
          operating_expenses: 800_000,
          ebit: 80_000,
          depreciation: 12_000,
          depreciation_amortization: 20_000,
          amortization: 8_000,
          interest_expense: 5_000,
          tax_expense: 20_000,
          owner_director_compensation: 90_000,
          personnel_costs: 420_000,
          rent_expense: 60_000,
          net_income: 55_000,
          total_assets: 2_500_000,
          current_assets: 700_000,
          fixed_assets: 1_800_000,
          cash: 150_000,
          accounts_receivable: 210_000,
          accounts_payable: 125_000,
          inventory: 85_000,
          total_liabilities: 1_000_000,
          current_liabilities: 350_000,
          short_term_debt: 75_000,
          total_debt: 600_000,
          total_equity: 1_500_000,
          minority_interest_result_share: -14_000,
          paid_up_capital: 250_000,
          capital_subsidies: 30_000,
          deferred_tax_liabilities: 45_000,
          buildings: 900_000,
          machinery_equipment: 350_000,
          other_provisions: 70_000,
          capex: 50_000,
          nwc_change: 15_000,
          operating_cash_flow: 135_000,
          investing_cash_flow: -50_000,
          financing_cash_flow: -20_000,
          free_cash_flow: 85_000,
        },
        historical_years_data: [
          { year: 2022, revenue: 900_000, ebitda: 70_000, reported_ebitda: 70_000 },
          { year: 2023, revenue: 1_000_000, ebitda: 80_000, reported_ebitda: 80_000 },
          { year: 2024, revenue: 1_100_000, ebitda: 90_000, reported_ebitda: 90_000 },
        ],
        forecast_years_data: [
          { year: 2026, revenue: 0, ebitda: 0, free_cash_flow: 110_000, is_forecast: true },
          { year: 2027, revenue: 0, ebitda: 0, free_cash_flow: 120_000, is_forecast: true },
        ],
        dcf_input_mode: 'fcff_only',
        dcf_revenue_growth_pct: 7,
        dcf_ebitda_margin_pct: 18,
        dcf_capex_pct: 4,
        dcf_da_pct: 3,
        dcf_nwc_pct: 2,
        dcf_tax_rate_pct: 25,
        dcf_wacc_pct: 11,
        dcf_terminal_growth_pct: 2,
        dcf_exit_multiple: 7.5,
        dcf_risk_free_rate_pct: 3.1,
        dcf_equity_risk_premium_pct: 5.5,
        dcf_beta: 1.2,
        dcf_cost_of_debt_pct: 5,
        dcf_debt_equity_pct: 35,
        dcf_tax_shield_pct: 25,
        dcf_discounting_convention: 'year_end',
        dcf_terminal_value_method: 'perpetual_growth',
        dcf_tax_shield_projections: [2_500, 2_000],
        government_bond_yield: 0.031,
        long_term_gdp_growth: 0.018,
        business_type_id: 'holding-company',
        business_type_segments: [
          { business_type_id: 'holding-company', weight: 60 },
          { business_type_id: 'property-company', weight: 40 },
        ],
        historical_ebitda_weighting_mode: 'weighted',
        historical_ebitda_weights: { 2022: 10, 2023: 20, 2024: 30, 2025: 40 },
        selected_method: 'upswitch_adaptive',
        user_weights: { adjusted_nav: 0.6, dcf: 0.4 },
        user_weight_justification: 'Holding assets dominate; DCF cross-checks the operating arm.',
        shares_for_sale: 62.5,
        owner_salary_addback: 35_000,
        owner_role: 'working',
        owner_dependency_factors: {
          client_concentration: 'medium',
          operational_knowledge: 'high',
          sales_relationship: 'high',
          technical_expertise: 'medium',
          industry_network: 'high',
          decision_making: 'high',
          brand_reputation: 'medium',
          process_documentation: 'low',
          team_capability: 'medium',
          succession_planning: 'low',
          business_scalability: 'medium',
          contract_transferability: 'high',
        },
        shareholder_roster: [
          {
            id: 'owner-1',
            display_name: 'Working owner',
            ownership_pct: 70,
            is_working_owner: true,
          },
          {
            id: 'owner-2',
            display_name: 'Passive owner',
            ownership_pct: 30,
            is_working_owner: false,
          },
        ],
        ownership_summary: {
          total_shareholder_count: 2,
          working_owner_count: 1,
          working_ownership_pct: 70,
          passive_shareholder_count: 1,
          passive_ownership_pct: 30,
        },
        holdings_consolidation: {
          parent: { id: 'holdco', lines: { total_equity: 1_500_000 } },
          subsidiaries: [
            { id: 'opco', ownership_pct: 80, lines: { revenue: 1_200_000, ebitda: 125_000 } },
          ],
          eliminations: { intercompany_receivable: 100_000 },
          mode: 'pro_rata',
        },
        tax_latencies: [
          {
            id: 'tax-property-2025',
            type: 'passive',
            description: 'Deferred tax on hidden property reserve',
            temporary_difference: 200_000,
            tax_rate: 25,
            status: 'accepted',
            evidence_id: 'evidence-tax-property-2025',
            reviewed_at: '2026-08-12T09:45:00Z',
            rule_version: 'equity-bridge-policy-v1',
            approved_by: 'advisor-17',
            currency: 'GBP',
            fiscal_year: 2025,
            effective_date: '2025-12-31',
          },
        ],
        balance_sheet_adjustments: [
          {
            id: 'bsa-investment',
            label: 'Non-operating investment',
            amount: 125_000,
            type: 'add',
            category: 'non_operating',
            status: 'verified',
            evidence_id: 'evidence-investment-2025',
            reviewed_at: '2026-08-12T09:50:00Z',
            rule_version: 'equity-bridge-policy-v1',
            approved_by: 'advisor-17',
            currency: 'GBP',
            fiscal_year: 2025,
            effective_date: '2025-12-31',
          },
        ],
        real_estate_treatment: 'included',
        real_estate_market_value: 1_100_000,
        real_estate_book_value: 900_000,
        nav_real_estate_adjustment: 200_000,
        nav_inventory_adjustment: -10_000,
        nav_hidden_reserves: 80_000,
        nav_goodwill_writeoff: -35_000,
        nav_receivables_adjustment: -20_000,
        nav_other_revaluations: 15_000,
        nav_tax_latency_pct: 25,
        nav_off_balance_items: -45_000,
        nav_real_estate_book_value: 900_000,
        nav_real_estate_appraisal_value: 1_100_000,
        nav_per_asset_tax_rates: { real_estate: 25, inventory: 20 },
        nav_equipment_revaluation: {
          original_cost: 350_000,
          acquisition_year: 2020,
          tax_book_value: 50_000,
          economic_useful_life_years: 10,
        },
        deal_type: 'compare',
        deal_goodwill_amount: 250_000,
        deal_seller_share_basis: 700_000,
        deal_seller_is_individual: true,
        deal_buyer_discount_rate_pct: 9,
        deal_registration_duty_pct: 12.5,
        saas_arr: 600_000,
        saas_mrr: 50_000,
        saas_arr_growth_pct: 20,
        saas_churn_pct: 6,
        saas_customer_churn_pct: 8,
        saas_nrr_pct: 112,
        saas_gross_margin_pct: 78,
        saas_cac: 4_000,
        saas_customer_concentration_pct: 22,
        saas_expansion_revenue_pct: 15,
        saas_sm_spend: 120_000,
        rev_recurring_pct: 50,
        rev_recurring_amount: 600_000,
        rev_top_client_concentration_pct: 10,
        rev_top_client_amount: 120_000,
        rev_contract_backlog: 300_000,
        rev_gross_churn_pct: 6,
        rev_capitalized_rd_amount: 85_000,
        multiple_calibration_adjustment: -0.5,
        multiple_calibration_note: 'Supplier concentration supported by contract review.',
        effective_multiple_override: 5.25,
        effective_multiple_override_note: 'Advisor-approved comparable-company reconciliation.',
        business_type_multiple_overrides: { 'holding-company': 4.5 },
        business_type_multiple_override_note: 'Entity-specific peer set.',
        show_enterprise_to_equity_bridge: false,
        asking_price_buffer_pct: 0.08,
        allow_untrusted_multiples_fallback: true,
        untrusted_multiples_fallback_reason: 'Disclosed shadow scenario only.',
        headline_value_basis: 'equity_value',
        has_audit: true,
        audited_financials: true,
        is_audited: true,
        liquidation_inputs: { preexisting_policy_id: 'liq-policy-v2' },
        liq_headcount: 19,
        liq_monthly_rent: 5_000,
        liq_paid_up_capital: 250_000,
        liq_deferred_tax: 45_000,
        liq_premise_override: 'orderly_liquidation',
        liq_realised_capital_gains: 40_000,
        liq_taxable_reserves: 30_000,
        liq_runway_months_orderly: 9,
        liq_runway_months_forced: 3,
        liq_distress_wacc_orderly: 18,
        liq_distress_wacc_forced: 30,
        liq_intangibles_uplift_pct: 5,
        liq_multiples_value_override: 425_000,
        liq_lb_super_preferent_employees: 10_000,
        liq_lb_preferent_tax: 20_000,
        liq_lb_preferent_other: 30_000,
        liq_lb_secured: 300_000,
        liq_lb_unsecured: 50_000,
        liq_lb_subordinated: 60_000,
        liq_lb_estate_costs: 70_000,
        liq_ao_land: 80_000,
        liq_ao_buildings: 1_100_000,
        liq_ao_machinery_equipment: 100_000,
        liq_ao_vehicles: 110_000,
        liq_ao_it_equipment: 120_000,
        liq_ao_intangibles: 130_000,
        liq_ao_inventory_raw: 140_000,
        liq_ao_inventory_wip: 150_000,
        liq_ao_inventory_finished: 160_000,
        liq_ao_trade_receivables: 170_000,
        liq_ao_other_receivables: 180_000,
        liq_ao_cash: 190_000,
        fiscal_inputs: { company_role: 'holding', internal_transfer: false },
        fiscal_acquisition_cost: 750_000,
        fiscal_anchor_2_value: 800_000,
        fiscal_anchor_3_value: 825_000,
        fiscal_anchor_4_value: 0,
        cap_table: {
          pre_money_target: 2_500_000,
          option_pool_pct: 10,
          safe_notes: [{ amount: 100_000, valuation_cap: 2_000_000 }],
        },
        investment_amount_sought: 500_000,
        metadata: {
          evidence_revision_id: 'evidence-rev-7',
          source_snapshot_id: 'hermes-snapshot-11',
        },
        valuation_case: {
          schema_version: 'valuation_case.v1',
          case_id: 'case-evidence-first-holdings',
          company_id: 'company-17',
          scenario_id: 'observed',
          evidence_revision_id: 'evidence-rev-7',
          policy_version: 'evidence_first_2026_08',
          input_decisions: [
            {
              schema_version: 'valuation_input_decision.v1',
              decision_id: 'decision-real-estate-perimeter-1',
              evidence_id: 'evidence-property-appraisal-1',
              field_key: 'real_estate_treatment',
              category: 'transaction_perimeter',
              state: 'accepted',
              currency: 'GBP',
              rule_version: 'real-estate-perimeter-v1',
              decided_by: 'advisor-17',
              decided_at: '2026-08-12T09:55:00Z',
            },
          ],
        },
      }),
      normalizations
    )

    const serialized = JSON.parse(JSON.stringify(request)) as typeof request

    expect(serialized).toMatchObject({
      currency: 'GBP',
      shares_for_sale: 62.5,
      number_of_employees: 19,
      number_of_owners: 2,
      selected_method: 'upswitch_adaptive',
      user_weights: { adjusted_nav: 0.6, dcf: 0.4 },
      government_bond_yield: 0.031,
      long_term_gdp_growth: 0.018,
      asking_price_buffer_pct: 0.08,
      multiple_calibration_adjustment: -0.5,
      multiple_calibration_note: 'Supplier concentration supported by contract review.',
      business_type_multiple_overrides: { 'holding-company': 4.5 },
      business_type_multiple_override_note: 'Entity-specific peer set.',
      show_enterprise_to_equity_bridge: false,
      has_audit: true,
      audited_financials: true,
      is_audited: true,
      metadata: {
        evidence_revision_id: 'evidence-rev-7',
        source_snapshot_id: 'hermes-snapshot-11',
      },
      valuation_case: {
        case_id: 'case-evidence-first-holdings',
        evidence_revision_id: 'evidence-rev-7',
        input_decisions: [
          expect.objectContaining({
            field_key: 'real_estate_treatment',
            state: 'accepted',
            evidence_id: 'evidence-property-appraisal-1',
            currency: 'GBP',
          }),
        ],
      },
    })
    expect(serialized.current_year_data).toMatchObject({
      operating_revenue: 1_175_000,
      ebitda: 125_000,
      reported_ebitda: 100_000,
      normalized_ebitda: 125_000,
      rent_expense: 60_000,
      operating_cash_flow: 135_000,
      investing_cash_flow: -50_000,
      financing_cash_flow: -20_000,
      minority_interest_result_share: -14_000,
      fixed_assets: 1_800_000,
      capital_subsidies: 30_000,
    })
    expect(serialized.current_year_data.ebitda_normalization_metadata.adjustments).toEqual([
      expect.objectContaining({
        id: 'norm-accepted',
        status: 'accepted',
        evidence_id: 'evidence-invoice-42',
        amount: 25_000,
      }),
      expect.objectContaining({
        id: 'norm-proposed',
        status: 'proposed',
        evidence_id: 'evidence-request-lease',
        amount: 10_000,
      }),
    ])
    expect(serialized.current_year_data.ebitda_normalization_metadata).toMatchObject({
      total_adjustments: 25_000,
      adjustment_count: 1,
      pending_adjustment_count: 1,
    })
    expect(serialized.normalizations).toEqual([
      expect.objectContaining({
        id: 'norm-accepted',
        fiscal_year: 2025,
        field: 'ebitda',
        original_value: 100_000,
        adjusted_value: 125_000,
        adjustment_amount: 25_000,
        status: 'accepted',
        evidence_id: 'evidence-invoice-42',
        currency: 'GBP',
      }),
      expect.objectContaining({
        id: 'norm-proposed',
        fiscal_year: 2025,
        original_value: 100_000,
        adjusted_value: 110_000,
        adjustment_amount: 10_000,
        status: 'proposed',
        evidence_id: 'evidence-request-lease',
        currency: 'GBP',
      }),
    ])
    expect(serialized.forecast_years_data).toEqual([
      expect.objectContaining({ year: 2026, free_cash_flow: 110_000, is_forecast: true }),
      expect.objectContaining({ year: 2027, free_cash_flow: 120_000, is_forecast: true }),
    ])
    expect(serialized.business_context).toMatchObject({
      dcf_wacc_pct: 11,
      dcf_discounting_convention: 'year_end',
      dcf_tax_shield_projections: [2_500, 2_000],
      dcf_terminal_value_method: 'perpetual_growth',
      nav_real_estate_book_value: 900_000,
      nav_real_estate_appraisal_value: 1_100_000,
      nav_per_asset_tax_rates: { real_estate: 25, inventory: 20 },
      nav_equipment_revaluation: expect.objectContaining({ original_cost: 350_000 }),
      deal_type: 'compare',
      deal_registration_duty_pct: 12.5,
      saas_arr: 600_000,
      rev_capitalized_rd_amount: 85_000,
    })
    expect(serialized.tax_latencies).toEqual([
      expect.objectContaining({
        id: 'tax-property-2025',
        status: 'accepted',
        evidence_id: 'evidence-tax-property-2025',
        reviewed_at: '2026-08-12T09:45:00Z',
        rule_version: 'equity-bridge-policy-v1',
        approved_by: 'advisor-17',
        currency: 'GBP',
        fiscal_year: 2025,
        effective_date: '2025-12-31',
      }),
    ])
    expect(serialized.balance_sheet_adjustments).toEqual([
      expect.objectContaining({
        id: 'bsa-investment',
        category: 'non_operating',
        status: 'verified',
        evidence_id: 'evidence-investment-2025',
        reviewed_at: '2026-08-12T09:50:00Z',
        rule_version: 'equity-bridge-policy-v1',
        approved_by: 'advisor-17',
        currency: 'GBP',
        fiscal_year: 2025,
        effective_date: '2025-12-31',
      }),
    ])
    expect(serialized.holdings_consolidation).toMatchObject({
      parent: { id: 'holdco' },
      subsidiaries: [expect.objectContaining({ id: 'opco', ownership_pct: 80 })],
      eliminations: { intercompany_receivable: 100_000 },
    })
    expect(serialized.owner_dependency_factors).toMatchObject({
      operational_knowledge: 'high',
      succession_planning: 'low',
    })
    expect(serialized.shareholder_roster).toHaveLength(2)
    expect(serialized.ownership_summary).toMatchObject({
      working_ownership_pct: 70,
      passive_ownership_pct: 30,
    })
    expect(serialized.liquidation_inputs).toMatchObject({
      preexisting_policy_id: 'liq-policy-v2',
      headcount: 19,
      monthly_rent: 5_000,
      liability_buckets: { secured: 300_000 },
      asset_overrides: { buildings: { adjusted_value: 1_100_000 } },
    })
    expect(serialized.liquidation_inputs).toMatchObject({
      realised_capital_gains: 40_000,
      taxable_reserves: 30_000,
      runway_months_orderly: 9,
      runway_months_forced: 3,
      distress_wacc_orderly: 18,
      distress_wacc_forced: 30,
      identifiable_intangibles_uplift_pct: 5,
      multiples_value_override: 425_000,
      liability_buckets: {
        super_preferent_employees: 10_000,
        preferent_tax: 20_000,
        unsecured: 50_000,
        subordinated: 60_000,
        estate_costs: 70_000,
      },
      asset_overrides: {
        land: { adjusted_value: 80_000 },
        machinery_equipment: { adjusted_value: 100_000 },
        cash: { adjusted_value: 190_000 },
      },
    })
    expect(serialized.fiscal_inputs).toEqual({
      company_role: 'holding',
      internal_transfer: false,
      acquisition_cost: 750_000,
      anchor_2_value: 800_000,
      anchor_3_value: 825_000,
      anchor_4_value: 0,
    })
    expect(serialized.cap_table).toMatchObject({
      pre_money_target: 2_500_000,
      option_pool_pct: 10,
    })
    expect(serialized.investment_amount_sought).toBe(500_000)
  })

  it('does not manufacture governance from a real-estate UI selection', () => {
    const request = buildValuationRequest(
      makeFormData({
        currency: 'EUR',
        real_estate_treatment: 'included',
        real_estate_market_value: 500_000,
        real_estate_book_value: 350_000,
        balance_sheet_adjustments: [
          {
            id: 'manual-excess-cash',
            label: 'Potential excess cash',
            amount: 50_000,
            type: 'add',
            category: 'excess_cash',
          },
        ],
      })
    )

    expect(request.valuation_case).toBeUndefined()
    expect(request.balance_sheet_adjustments?.[0]).not.toHaveProperty('status')
    expect(request.balance_sheet_adjustments?.[0]).not.toHaveProperty('evidence_id')
  })
})
