/**
 * Identifier Utilities
 *
 * Centralized utilities for identifying report/session ID formats.
 * These utilities are used across the codebase to determine how to
 * look up sessions and reports.
 *
 * ID Formats:
 * - Session Key: 'val_xxx' format (e.g., 'val_1769197369597_vwfre4ljar')
 * - UUID: Standard UUID format (e.g., 'c61f49cf-3320-41d8-84c5-e4f874edaad2')
 *
 * Sources:
 * - Session keys come from Venus when creating new sessions
 * - UUIDs come from Mercury when navigating to existing reports (valuation_reports.id)
 *
 * @module utils/identifiers
 */

/**
 * UUID regex pattern for validation
 * Matches: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (36 characters)
 */
export const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

/**
 * Session key prefix used by Venus
 */
export const SESSION_KEY_PREFIX = 'val_'

/**
 * Check if a string is a valid UUID format
 *
 * UUIDs are used as the primary key for valuation_reports.
 * Mercury passes these when navigating to existing reports.
 *
 * @param str - String to check
 * @returns true if the string is a valid UUID format
 *
 * @example
 * isUuid('c61f49cf-3320-41d8-84c5-e4f874edaad2') // true
 * isUuid('val_1769197369597_vwfre4ljar') // false
 * isUuid('') // false
 */
export function isUuid(str: string | null | undefined): boolean {
  if (!str) return false
  return UUID_REGEX.test(str)
}

/**
 * Check if a string is a session key format (val_xxx)
 *
 * Session keys are generated by Venus when creating new valuation sessions.
 * They're stored in valuation_sessions.session_key.
 *
 * @param str - String to check
 * @returns true if the string starts with 'val_'
 *
 * @example
 * isSessionKey('val_1769197369597_vwfre4ljar') // true
 * isSessionKey('c61f49cf-3320-41d8-84c5-e4f874edaad2') // false
 * isSessionKey('') // false
 */
export function isSessionKey(str: string | null | undefined): boolean {
  if (!str) return false
  return str.startsWith(SESSION_KEY_PREFIX)
}

/**
 * Determine the type of identifier
 *
 * @param str - String to check
 * @returns 'uuid' | 'session_key' | 'unknown'
 *
 * @example
 * getIdentifierType('c61f49cf-3320-41d8-84c5-e4f874edaad2') // 'uuid'
 * getIdentifierType('val_1769197369597_vwfre4ljar') // 'session_key'
 * getIdentifierType('some-random-string') // 'unknown'
 */
export function getIdentifierType(
  str: string | null | undefined
): 'uuid' | 'session_key' | 'unknown' {
  if (isSessionKey(str)) return 'session_key'
  if (isUuid(str)) return 'uuid'
  return 'unknown'
}

/**
 * Check if a string looks like an existing report identifier
 *
 * Returns true if the identifier is either:
 * - A valid UUID (from Mercury navigation)
 * - A session key (val_xxx from Venus)
 *
 * This is used to determine if we should skip credit checks
 * (existing reports don't need credit validation).
 *
 * @param str - String to check
 * @param excludeTemp - If true, excludes temporary IDs containing '_temp'
 * @returns true if the string looks like an existing report ID
 *
 * @example
 * looksLikeExistingReportId('val_1769197369597_vwfre4ljar') // true
 * looksLikeExistingReportId('c61f49cf-3320-41d8-84c5-e4f874edaad2') // true
 * looksLikeExistingReportId('new') // false
 */
export function looksLikeExistingReportId(
  str: string | null | undefined,
  excludeTemp: boolean = true
): boolean {
  if (!str) return false
  if (excludeTemp && str.includes('_temp')) return false
  return isSessionKey(str) || isUuid(str)
}

/**
 * Detect if URL pathname indicates an existing report
 *
 * Checks the current URL for patterns that indicate an existing report:
 * - /reports/{uuid} - UUID format from Mercury
 * - /reports/val_xxx - Session key format from Venus
 *
 * @returns true if the URL indicates an existing report
 *
 * @example
 * // URL: /en/reports/c61f49cf-3320-41d8-84c5-e4f874edaad2
 * detectExistingReportFromUrl() // true
 *
 * // URL: /en/reports/val_1769197369597_vwfre4ljar
 * detectExistingReportFromUrl() // true
 *
 * // URL: /en/reports/new
 * detectExistingReportFromUrl() // false
 */
export function detectExistingReportFromUrl(): boolean {
  if (typeof window === 'undefined') return false

  const pathname = window.location.pathname

  // Check for report UUID in URL path: /reports/{uuid} or /en/reports/{uuid}
  if (UUID_REGEX.test(pathname.split('/').pop() || '')) {
    return true
  }

  // Check for session key in URL path: /reports/val_xxx
  const lastSegment = pathname.split('/').pop() || ''
  if (lastSegment.startsWith(SESSION_KEY_PREFIX)) {
    return true
  }

  return false
}
