/** Localized copy for the negative-EBITDA recovery workflow. */
export const NEGATIVE_EBITDA_RECOVERY_COPY = {
  nl: {
    eyebrow: 'Herstelwaardering',
    title: 'Negatieve EBITDA vraagt een ander waarderingspad',
    intro:
      'We beoordelen eerst normalisaties. Blijft EBITDA negatief, dan toetsen we herstel, omzetkwaliteit en een eventuele activabodem afzonderlijk.',
    reported: 'Gerapporteerde EBITDA',
    normalized: 'Genormaliseerde EBITDA',
    normalization: 'Controleer normalisaties',
    start: 'Bouw herstelplanning',
    scenarios: 'Scenario’s',
    funding: 'Financiering',
    assumptions: 'Aannames',
    verification: 'Verificatie',
    probability: 'Kans',
    probabilityOk: 'Kansen tellen op tot 100%',
    probabilityBad: 'Kansen moeten exact 100% zijn',
    year: 'Jaar',
    revenue: 'Omzet',
    opex: 'Operationele kosten excl. D&A',
    da: 'D&A',
    tax: 'Belasting %',
    nol: 'Openings-NOL',
    capex: 'CapEx',
    nwc: 'Δ werkkapitaal',
    units: 'Eenheden',
    price: 'Prijs per eenheid',
    driverModel: 'Omzetdriver',
    customerAcv: 'Klanten × contractwaarde',
    consultantCapacity: 'Consultants × capaciteit × bezetting × tarief',
    arrRetention: 'ARR-retentie en uitbreiding',
    unitsPrice: 'Eenheden × prijs',
    customDriver: 'Aangetoond aangepast model',
    customers: 'Klanten',
    acv: 'Jaarlijkse contractwaarde',
    consultants: 'Consultants',
    annualCapacity: 'Jaarcapaciteit per consultant',
    utilization: 'Bezetting %',
    rate: 'Tarief',
    openingArr: 'Openings-ARR',
    retention: 'Brutoretentie %',
    expansionArr: 'Uitbreidings-ARR',
    newArr: 'Nieuwe ARR',
    modelName: 'Naam van het model',
    derivedRevenue: 'Afgeleide omzet',
    customEvidence: 'Bewijs voor het aangepaste model',
    reconciled: 'Omzetdriver sluit aan',
    unreconciled: 'Omzetdriver sluit niet aan',
    addYear: 'Voeg prognosejaar toe',
    openingCash: 'Beschikbare openingscash',
    minimumCash: 'Minimale cashbuffer',
    commitment: 'Toegezegde financiering',
    addCommitment: 'Voeg financiering toe',
    amount: 'Bedrag',
    source: 'Bron',
    evidence: 'Bewijsreferentie(s), gescheiden door komma’s',
    timing: 'Beschikbaar in jaar',
    wacc: 'WACC %',
    growth: 'Terminale groei %',
    assumptionEvidence: 'Bron voor WACC en terminale aannames',
    attestOwner:
      'Ik bevestig dat deze planning mijn actuele, oprecht haalbare herstelplan weerspiegelt.',
    attestAdvisor:
      'Ik bevestig dat ik deze planning professioneel heb beoordeeld en de bronnen heb gecontroleerd.',
    ready: 'Compleet voor ondertekende berekening',
    missing: 'Nog vereist',
    result: 'Herstelbeoordeling',
    noRange: 'Nog geen verdedigbare waarderingsrange vastgesteld',
    currentEquity: 'Huidige aandelenwaarde',
    enterpriseValue: 'Ondernemingswaarde',
    primaryMethod: 'Primaire methode',
    crossChecks: 'Kruiscontroles',
    conflicts: 'Trajectsignalen',
    qualifications: 'Waarderingskwalificaties',
    fundingGap: 'Financieringsbehoefte',
    breakEven: 'Break-evenjaar',
    terminalShare: 'Aandeel terminale waarde',
    blockers: 'Blokkerende punten',
    evidenceNeeded: 'Aanvullend bewijs voor hogere betrouwbaarheid',
    actions: 'Volgende acties',
    scenarioOutcome: 'Scenario-uitkomst',
  },
  en: {
    eyebrow: 'Recovery valuation',
    title: 'Negative EBITDA requires a different valuation path',
    intro:
      'We assess normalizations first. If EBITDA remains negative, recovery, revenue quality and any asset floor are tested independently.',
    reported: 'Reported EBITDA',
    normalized: 'Normalized EBITDA',
    normalization: 'Review normalizations',
    start: 'Build recovery plan',
    scenarios: 'Scenarios',
    funding: 'Funding',
    assumptions: 'Assumptions',
    verification: 'Verification',
    probability: 'Probability',
    probabilityOk: 'Probabilities add up to 100%',
    probabilityBad: 'Probabilities must equal exactly 100%',
    year: 'Year',
    revenue: 'Revenue',
    opex: 'Operating expenses excl. D&A',
    da: 'D&A',
    tax: 'Tax %',
    nol: 'Opening NOL',
    capex: 'CapEx',
    nwc: 'Δ working capital',
    units: 'Units',
    price: 'Price per unit',
    driverModel: 'Revenue driver',
    customerAcv: 'Customers × contract value',
    consultantCapacity: 'Consultants × capacity × utilization × rate',
    arrRetention: 'ARR retention and expansion',
    unitsPrice: 'Units × price',
    customDriver: 'Evidence-backed custom model',
    customers: 'Customers',
    acv: 'Annual contract value',
    consultants: 'Consultants',
    annualCapacity: 'Annual capacity per consultant',
    utilization: 'Utilization %',
    rate: 'Rate',
    openingArr: 'Opening ARR',
    retention: 'Gross retention %',
    expansionArr: 'Expansion ARR',
    newArr: 'New ARR',
    modelName: 'Model name',
    derivedRevenue: 'Derived revenue',
    customEvidence: 'Custom-model evidence',
    reconciled: 'Revenue driver reconciles',
    unreconciled: 'Revenue driver does not reconcile',
    addYear: 'Add forecast year',
    openingCash: 'Opening cash available',
    minimumCash: 'Minimum cash buffer',
    commitment: 'Committed funding',
    addCommitment: 'Add funding commitment',
    amount: 'Amount',
    source: 'Source',
    evidence: 'Evidence reference(s), comma separated',
    timing: 'Available in year',
    wacc: 'WACC %',
    growth: 'Terminal growth %',
    assumptionEvidence: 'Source for WACC and terminal assumptions',
    attestOwner: 'I confirm this schedule reflects my current, genuinely achievable recovery plan.',
    attestAdvisor:
      'I confirm that I professionally reviewed this schedule and checked its evidence.',
    ready: 'Complete for signed calculation',
    missing: 'Still required',
    result: 'Recovery assessment',
    noRange: 'No defensible valuation range established yet',
    currentEquity: 'Current equity value',
    enterpriseValue: 'Enterprise value',
    primaryMethod: 'Primary method',
    crossChecks: 'Cross-checks',
    conflicts: 'Trajectory signals',
    qualifications: 'Valuation qualifications',
    fundingGap: 'Funding requirement',
    breakEven: 'Break-even year',
    terminalShare: 'Terminal-value share',
    blockers: 'Blocking items',
    evidenceNeeded: 'Additional evidence for higher confidence',
    actions: 'Next actions',
    scenarioOutcome: 'Scenario outcome',
  },
  fr: {
    eyebrow: 'Valorisation de redressement',
    title: 'Un EBITDA négatif exige une autre approche de valorisation',
    intro:
      'Nous examinons d’abord les normalisations. Si l’EBITDA reste négatif, le redressement, la qualité du chiffre d’affaires et le plancher d’actifs sont testés séparément.',
    reported: 'EBITDA publié',
    normalized: 'EBITDA normalisé',
    normalization: 'Vérifier les normalisations',
    start: 'Construire le plan de redressement',
    scenarios: 'Scénarios',
    funding: 'Financement',
    assumptions: 'Hypothèses',
    verification: 'Vérification',
    probability: 'Probabilité',
    probabilityOk: 'Les probabilités totalisent 100 %',
    probabilityBad: 'Les probabilités doivent totaliser exactement 100 %',
    year: 'Année',
    revenue: 'Chiffre d’affaires',
    opex: 'Charges d’exploitation hors D&A',
    da: 'D&A',
    tax: 'Impôt %',
    nol: 'Pertes fiscales initiales',
    capex: 'CapEx',
    nwc: 'Δ fonds de roulement',
    units: 'Unités',
    price: 'Prix par unité',
    driverModel: 'Moteur de chiffre d’affaires',
    customerAcv: 'Clients × valeur contractuelle',
    consultantCapacity: 'Consultants × capacité × utilisation × tarif',
    arrRetention: 'Rétention et expansion ARR',
    unitsPrice: 'Unités × prix',
    customDriver: 'Modèle personnalisé étayé',
    customers: 'Clients',
    acv: 'Valeur contractuelle annuelle',
    consultants: 'Consultants',
    annualCapacity: 'Capacité annuelle par consultant',
    utilization: 'Utilisation %',
    rate: 'Tarif',
    openingArr: 'ARR initial',
    retention: 'Rétention brute %',
    expansionArr: 'ARR d’expansion',
    newArr: 'Nouvel ARR',
    modelName: 'Nom du modèle',
    derivedRevenue: 'Chiffre d’affaires dérivé',
    customEvidence: 'Preuve du modèle personnalisé',
    reconciled: 'Le moteur de chiffre d’affaires concorde',
    unreconciled: 'Le moteur de chiffre d’affaires ne concorde pas',
    addYear: 'Ajouter une année prévisionnelle',
    openingCash: 'Trésorerie initiale disponible',
    minimumCash: 'Trésorerie minimale',
    commitment: 'Financement engagé',
    addCommitment: 'Ajouter un financement',
    amount: 'Montant',
    source: 'Source',
    evidence: 'Référence(s) probante(s), séparées par des virgules',
    timing: 'Disponible en',
    wacc: 'WACC %',
    growth: 'Croissance terminale %',
    assumptionEvidence: 'Source du WACC et des hypothèses terminales',
    attestOwner: 'Je confirme que ce plan reflète un redressement actuel et réellement réalisable.',
    attestAdvisor: 'Je confirme avoir examiné ce plan professionnellement et vérifié ses preuves.',
    ready: 'Complet pour le calcul signé',
    missing: 'Encore requis',
    result: 'Évaluation du redressement',
    noRange: 'Aucune fourchette de valorisation défendable établie à ce stade',
    currentEquity: 'Valeur actuelle des capitaux propres',
    enterpriseValue: "Valeur d'entreprise",
    primaryMethod: 'Méthode principale',
    crossChecks: 'Contrôles croisés',
    conflicts: 'Signaux de trajectoire',
    qualifications: 'Réserves de valorisation',
    fundingGap: 'Besoin de financement',
    breakEven: 'Année du seuil de rentabilité',
    terminalShare: 'Part de la valeur terminale',
    blockers: 'Points bloquants',
    evidenceNeeded: 'Preuves complémentaires pour une fiabilité accrue',
    actions: 'Actions suivantes',
    scenarioOutcome: 'Résultat par scénario',
  },
} as const
